version: '3'
services:
    

    tip-api:
        image: "${REGISTRY_URL:-gameapp}/tipp-api:${IMAGE_TAG:-latest}"
        build: ./TippApi
        networks: 
            - gameapp-network
        labels:
            - "traefik.enable=true" # Enable publishing this service by Traefik
            - "traefik.http.routers.tip-api.rule=PathPrefix(`/guess`)" # Routing rule

    toplista-api:
        image: "${REGISTRY_URL:-gameapp}/toplista-api:${IMAGE_TAG:-latest}"
        build: ./TopListaApi
        networks: 
            - gameapp-network
        labels:
            - "traefik.enable=true" # Enable publishing this service by Traefik
            - "traefik.http.routers.toplista-api.rule=PathPrefix(`/toplist`)" # Routing rule

    frontend:
        image: "${REGISTRY_URL:-gameapp}/frontend:${IMAGE_TAG:-latest}"
        ports: 
            - '8080:80'
        build: 
            context: .
            dockerfile: frontend/Docker/Dockerfile
        labels: 
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=PathPrefix(`/`)" # Routing rule   
        networks: 
            - gameapp-network

    kiertekelo:
        image: "${REGISTRY_URL:-gameapp}/kiertekelo:${IMAGE_TAG:-latest}"
        build: ./Kiertekelo
        networks: 
            - gameapp-network


    